### ISSUE TITLE
🐛 Bug ➾NodeJS v18 not supported

### ISSUE THREAD

**Issue by michaelkernaghan** [pinnacle-labs/taqueria#1501]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I tried to use the Taco-shop scaffold, but when it came time to start the dapp, I got a failure. I was using  node v18.4.0 (npm v8.12.1)

The Taqueria Scaffold requirement says  Node.js v16.17.1 or later, but this is to correct as node v18.4.0 (npm v8.12.1) fails with an error.  If I switch to   node v16.17.1 (npm v8.15.0) it works fine

### 🆘 Steps to Reproduce?

1. use nvm 18.4.0
2.  start the dapp in the Taco-Shop Scaffold 
3.   error
4. switch to node v16.17.1
5.  start the dapp it works fine
6. note docs say " Node.js v16.17.1 or later" which is shown above is not correct

### 🪵 Relevant log output

```shell
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/mike/taco-shop/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/mike/taco-shop/app/node_modules/react-scripts/scripts/start.js:19
  throw err;
```
```


### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

if they use npm 18+

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.24.1

### 🌿 Node.js Version

v18.4.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Fixed. NodeJS v20 is also supported.
